# wpa_supplicant configuration for wired IEEE 802.1X.
# Default smoke test = EAP-MD5 (no certificate required).

ctrl_interface=/var/run/wpa_supplicant
eapol_version=2
ap_scan=0
fast_reauth=1

# EAP-DID test
network={
    key_mgmt=IEEE8021X
    eapol_flags=0
    eap=DID
    identity="user@inst.tld"
}

# EAP-MD5 smoke test
network={
    key_mgmt=IEEE8021X
    eapol_flags=0
    eap=MD5
    identity="user@inst.tld"
    password="testpass"
}
