driver=none
interface=lo
eap_server=1
eap_user_file=/etc/hostapd/hostapd.eap_user
radius_server_clients=/etc/hostapd/radius_clients
radius_server_auth_port=1812
logger_stdout=-1
logger_stdout_level=1
ca_cert=/etc/certs/ca.pem
server_cert=/etc/certs/server.pem
private_key=/etc/certs/server-key.pem
max_auth_rounds_short=2000
max_auth_rounds=4000
